
### 1. REGISTER USER
# POST http://localhost:8080/api/users
# Content-Type: application/json

# {
#   "email": "leo@gmail.com",
#   "password": "123456",
#   "username": "Leo"
# }

# ---

# ### 2. LOGIN USER
# POST http://localhost:8080/auth/login
# Content-Type: application/json

# {
#   "email": "leo@gmail.com",
#   "password": "123456"
# }

# ### Expected Response
# # {
# #   "response": {
# #     "token": "eyJhbGciOiJIUzI1NiJ9..."
# #   },
# #   "status": {
# #     "statusCode": 200,
# #     "statusMessage": "Login successful"
# #   }
# # }


### 4. GET USER PROFILE (PROTECTED API)
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzRjBJMVNFMkVYUlZJNFMzIiwiaWF0IjoxNzgyNTc4NTgwLCJleHAiOjE3ODI1ODkzODB9.ueBg5ZjLnWu3otEVInrOMeyo7qcvnTFZtWMpQgjGpRk
