spring.application.name=whereitgo

# Database connection URL
spring.datasource.url=
# Database credentials
spring.datasource.username=
spring.datasource.password=

# PostgreSQL Driver (Optional: Spring Boot usually auto-detects this)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
