spring.application.name=whereitgo

# Database connection URL
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.xbtwbubfvhhehijeawft&password=Gautham@28072002!!!

# Database credentials
spring.datasource.username=
spring.datasource.password=

# PostgreSQL Driver (Optional: Spring Boot usually auto-detects this)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=INFO
logging.level.com.wig=DEBUG
logging.level.org.springframework.security=DEBUG
logging.file.name=logs/application.log

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

server.servlet.session.cookie.same-site=strict
jwt.secret=k9F3sL8vQ2mX7zP1aR6tY4uW8nC5bJ0d

# Predefined Provider (GitHub)
# spring.security.oauth2.client.registration.github.client-id=Ov23lizLZAFXwlLdfo0A
# spring.security.oauth2.client.registration.github.client-secret=22f42599928c1fb8ad57eafecc3ccce9f6175841
