spring.application.name=whereitgo

# Database connection URL
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.xbtwbubfvhhehijeawft&password=Gautham@28072002!!!

# Database credentials
spring.datasource.username=
spring.datasource.password=

# PostgreSQL Driver (Optional: Spring Boot usually auto-detects this)
spring.datasource.driver-class-name=org.postgresql.Driver
